# Generated by Django 4.2.6 on 2023-10-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_rating_user_alter_rating_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamp']},
        ),
    ]
